export const ADD_INGREDIENT_TO_CURRENTS = 'ADD_INGREDIENT_TO_CURRENTS'
export const REMOVE_INGREDIENT_FROM_CURRENTS = 'REMOVE_INGREDIENT_FROM_CURRENTS'
export const ADD_BUN = 'ADD_BUN'
export const SORT_CURRENT_INGREDIENT = 'SORT_CURRENT_INGREDIENT'
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
